---
title: Workfront Fusion：シナリオ接続エラー
description: 特定のシナリオの実行が失敗し、「接続を検証できませんでした」というエラーメッセージが表示されます。
hidefromtoc: true
feature: Workfront Fusion
exl-id: 53edb587-86ab-4515-90b3-c2a338eadfc3
source-git-commit: 003a38b5009e80e1b65c23354c8fb9b38d6a7819
workflow-type: tm+mt
source-wordcount: '57'
ht-degree: 100%

---

# Workfront Fusion：シナリオ接続エラー

>[!NOTE]
>
>このイシューは再現できなかったため、クローズされました。

特定のシナリオの実行が失敗し、「接続を検証できませんでした」というエラーメッセージが表示されます。

_最初に報告されたのは 2025年2月19日（PT）です。_
